"""Temporary cookie-file support for downloader subprocesses."""

from __future__ import annotations

import os
import tempfile
import time
from collections.abc import Iterator, Mapping
from contextlib import contextmanager
from pathlib import Path


COOKIE_DOMAIN = ".instagram.com"
COOKIE_EXPIRY = 2_147_483_647


def _cookie_value(value: str) -> str:
    return str(value).replace("\t", " ").replace("\n", "")


@contextmanager
def downloader_cookie_file(cookies: Mapping[str, str] | None) -> Iterator[Path | None]:
    """Writes a temporary Netscape cookie file and removes it after use."""
    if not cookies:
        yield None
        return

    fd, raw_path = tempfile.mkstemp(prefix="archiver-downloader-cookies-", suffix=".txt")
    path = Path(raw_path)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as file:
            file.write("# Netscape HTTP Cookie File\n")
            file.write(f"# Generated by Instagram Archiver at {int(time.time())}\n")
            for name, value in sorted(cookies.items()):
                if not name or value is None:
                    continue
                file.write(
                    "\t".join(
                        [
                            COOKIE_DOMAIN,
                            "TRUE",
                            "/",
                            "TRUE",
                            str(COOKIE_EXPIRY),
                            _cookie_value(name),
                            _cookie_value(str(value)),
                        ]
                    )
                    + "\n"
                )
        os.chmod(path, 0o600)
        yield path
    finally:
        try:
            path.unlink()
        except FileNotFoundError:
            pass
